# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: '2'
services:
  firefox:
    image: selenium/node-firefox:3.12.0-cobalt
    networks:
        - dockernet3
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      NODE_MAX_SESSION: 10
      NODE_MAX_INSTANCES: 10
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.12.0-cobalt
    networks:
        - dockernet3
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      NODE_MAX_SESSION: 10
      NODE_MAX_INSTANCES: 10
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.12.0-cobalt
    networks:
        - dockernet3
    environment:
      NODE_MAX_SESSION: 10
      NODE_MAX_INSTANCES: 10
    ports:
      - "4441:4444"
           
networks:
    dockernet3:
        external: true